inputs:
  release:
    required: true
    type: string

runs:
  using: composite
  steps:
    -
      run: |
        echo 'Build: ${{ inputs.release }}'
      shell: bash
    -
      run: |
        echo 'Deploy: ${{ inputs.release }}'
      shell: bash
