name: Test the execution Python script

on:
  push:
    paths:
      - .github/workflows/test-run-python-script.yml

env:
  VERSION_PATTERN: '^\d+$'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      -
        name: Execute inline script
        run: |
          import os
          import re
          
          match = re.search(os.environ['VERSION_PATTERN'], '123')
          print(match)
        shell: python
