on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        run: |
          echo 'Build: ${{ inputs.release }}'
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        run: |
          echo 'Deploy: ${{ inputs.release }}'
