name: Check and build new s6 version

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  push:
    paths:
      - .github/workflows/checker.yml
      - scripts/main.js

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest
    env:
      VERSION_PATTERN: ARG\s+S6_OVERLAY_VERSION=\"(.+)\"
    steps:
    -
      name: Git checkout
      uses: actions/checkout@v3
    -
      name: Get current version
      id: curver
      run: |
        sed -nr "s/${{ env.VERSION_PATTERN }}/value=\1/p" \
            Dockerfile \
            >> $GITHUB_OUTPUT
    -
      name: Get latest version
      id: lastver
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('./scripts/main.js')
          await script({github, core})
    - run: echo ${{ steps.curver.outputs.value }}
    - run: echo ${{ steps.lastver.outputs.value }}
