name: Check and build new s6 version

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  push:
    paths:
      - .github/workflows/checker.yml
      - scripts/main.js

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      VERSION_PATTERN: (ARG\s+S6_OVERLAY_VERSION)=(\"|')(.+)\2
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get current version
        id: curver
        run: |
          sed -nr "s/${{ env.VERSION_PATTERN }}/value=\3/p" \
              Dockerfile \
              >> $GITHUB_OUTPUT
      -
        name: Get latest version
        id: lastver
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/main.js')
            await script({github, core})
      -
        name: Set update state
        id: update
        run: |
          echo "state=${{ steps.lastver.outputs.value > steps.curver.outputs.value }}" \
          >> $GITHUB_OUTPUT
      -
        name: Update version in Dockerfile
        if: ${{ steps.update.outputs.state }}
        run: |
          sed -ri \
              "s/${{ env.VERSION_PATTERN }}/\1=\2${{ steps.lastver.outputs.value }}\2/" \
              Dockerfile
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.update.outputs.state }}
        env:
          MESSAGE: |
            Bump s6-overlay
            from ${{ steps.curver.outputs.value }}
            to ${{ steps.lastver.outputs.value }}
        with:
          branch: checker/latest-version
          delete-branch: true
          title: ${{ env.MESSAGE }}
          commit-message: ${{ env.MESSAGE }}
          labels: |
            automated pr
          body: |
            ${{ steps.lastver.outputs.body }}
            ${{ steps.lastver.outputs.url }}
