name: Compile Golang program for multiarch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux']
        arch: ['amd64', 'arm']
    defaults:
      run:
        working-directory: ./program/hello-github
    steps:
      - uses: actions/checkout@v3
      - run: git log --all
      # - run: git diff --name-only HEAD~1 HEAD --
      # - name: Find changes
      #   run: |
      #     git diff --name-only HEAD^ HEAD \
      #       | xargs -L1 dirname \
      #       | uniq \
      #       | while read p; do find "$p" -name Makefile; done

      # - run: make
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.20.2'
      # - name: Compile
      #   env:
      #     GOOS: ${{ matrix.os }}
      #     GOARCH: ${{ matrix.arch }}
      #   run: |
      #     go build \
      #       -v \
      #       -o ./hello-${{ matrix.os }}-${{ matrix.arch }} \
      #       ./hello.go
      # - name: Commit
      #   run: |
      #     git config --local user.email "noreply@github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Update program"
      # -
      #   name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     force: true
