name: Compile Golang program for multiarch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: linux
        arch: ['amd64', 'arm']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'
      - name: Compile
        env:
          GOOS=${{ matrix.os }}
          GOARCH=${{ matrix.arch }}
        run: |
          go build \
            -o ./program/hello-${{ matrix.os }}-${{ matrix.arch }} \
            ./program/hello.go
      - run: ./program/hello