name: Test

on:
  push

jobs:
  test:
    strategy:
      matrix:
        release:
          - "bookworm-slim"
          - "bullseye-slim"
          - "buster-slim"
    runs-on: ubuntu-latest
    steps:
      -
        name: My first step - check out repository
        uses: actions/checkout@v4
      -
        if: ${{ matrix.release != 'buster-slim' }}
        uses: ./.github/actions/build-image
        with:
          release: ${{ matrix.release }}
