name: Loading data for matrix from JSON file

on: push

jobs:
  load:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Load JSON file
        id: set-matrix
        working-directory: ./.github/workflows
        run: echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT
  job:
    needs: load
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.load.outputs.matrix) }}
    steps:
      -
        run: echo ${{ matrix.version }}
