name: Testing the creation of a pull request

on:
  push:
    paths:
      - .github/workflows/test-create-pull-request.yml

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create commits
        run: |
          git config user.name 'Kirill Vercetti'
          git config user.email 'office@kyzima-spb.com'
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A .
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
