name: Test

on:
  push

jobs:
  test:
    strategy:
      matrix:
        release:
          - "bookworm-slim"
          - "bullseye-slim"
          - "buster-slim"
    uses: ./.github/workflows/build.yml
    with:
      release: ${{ matrix.release }}