name: Loading data for matrix from JSON file

on: push

env:
  IMAGE_NAME: "tixati"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Load JSON file
        id: load
        working-directory: ./.github/workflows
        run: echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT
  job:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.version }}
          flavor: |
            latest=auto
            # latest=${{ matrix.release == 'bullseye-slim' }}
      -
        run: echo "${{ steps.meta.outputs.tags }}"
