name: Test Docker

on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Path to $GITHUB_ENV
        run: readlink -f $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      -
        name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64
          tags: test:amd64
          #load: true
      -
        name: Test amd64
        run: docker run --rm test:amd64 uname -a
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/arm/v7
          tags: test:armv7
          load: true
      -
        name: Test arm/v7
        run: docker run --rm --platform linux/arm/v7 test:armv7 uname -a

